name: Docker image (latest-dev)

on:
  push:
    branches:
      - lifecyclehooktest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get repository variable in lowercase
      run: echo "REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
  
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        push: true
        file: dockerfiles/Dockerfile.dev-self-contained
        tags: ghcr.io/${{ env.REPOSITORY }}:latest